/* CREATE DATABASE RoyougiChan */
CREATE DATABASE `RyougiChan` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE RyougiChan;

/* CREATE TABLE R_Article */
DROP TABLE IF EXISTS `R_Article`;

CREATE TABLE IF NOT EXISTS `R_Article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `subTitle` VARCHAR(120),
  `author` VARCHAR(100) NOT NULL,
  `editor` VARCHAR(100) NOT NULL,
  `authorDesc` VARCHAR(150),
  `license` VARCHAR(100),
  `addLicense` VARCHAR(100),
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` DATETIME NOT NULL,
  `abstract` VARCHAR(2000),
  `categorys` VARCHAR(200),
  `keywords` VARCHAR(200),
  `content` MEDIUMTEXT NOT NULL,
  `reference` MEDIUMTEXT,
  `cover` VARCHAR(150),
  `isDraft` BIT(1) NOT NULL DEFAULT 0,
  `readCount` int NOT NULL DEFAULT 0,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

/* CREATE TABLE R_User */
DROP TABLE IF EXISTS `R_User`;

CREATE TABLE IF NOT EXISTS `R_User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100),
  `password` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(100) NOT NULL,
  `gender` INT NOT NULL DEFAULT 0,
  `birthday` DATETIME,
  `region` VARCHAR(100),
  `description` VARCHAR(150),
  `regTime` DATETIME NOT NULL,
  `latestLoginTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `latestLoginIP` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

/* CREATE TABLE R_Admin */
DROP TABLE IF EXISTS `R_Admin`;

CREATE TABLE IF NOT EXISTS `R_Admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(100) NOT NULL,
  `latestLoginTime` DATETIME NOT NULL,
  `latestLoginIP` VARCHAR(100) NOT NULL,
  `authority` VARCHAR(100),
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

/* CREATE TABLE R_NavBar */
DROP TABLE IF EXISTS `R_NavBar`;
CREATE TABLE `R_NavBar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `level` INT NOT NULL DEFAULT 1,
  `index` INT NOT NULL DEFAULT 1,
  `parentID` INT,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

/* CREATE TABLE R_SideBar */
DROP TABLE IF EXISTS `R_SideBar`;
CREATE TABLE `R_SideBar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `level` INT NOT NULL DEFAULT 1,
  `index` INT NOT NULL DEFAULT 1,
  `parentID` INT,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;

/* CREATE TABLE R_Comment */
DROP TABLE IF EXISTS `R_Comment`;
CREATE TABLE `R_Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articleID` INT NOT NULL,
  `userID` INT NOT NULL,
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content` VARCHAR(500) NOT NULL,
  `replyFor` INT,
  `voteUp` INT NOT NULL DEFAULT 0,
  `voteDown` INT NOT NULL DEFAULT 0,
  PRIMARY KEY `pk_id`(`id`)
) ENGINE = InnoDB;
